spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/std_ms_db
    username: postgres
    password: Sovita#28
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#Local Testing
baseUrl_img: https://localhost:8080/api/v1/images?fileName=
dashboard_url: https://localhost:8080
file_path: src/main/resources/storage